name: CI - Java Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure Maven runs from the correct directory
        run: pwd && ls -la  # Esto mostrará la estructura del repositorio en el log

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'  # Se puede ajustar según sea necesario

      - name: Install dependencies
        run: mvn install

      - name: Run tests
        run: mvn test
